# Generated by Django 5.2.1 on 2025-07-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
