# Generated by Django 5.2 on 2025-07-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
